# Check key balances on Sepolia.
#
name: Check sepolia funds
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-check:
    runs-on: [self-hosted, Linux, X64, SystemTestRunner2]
    steps:
      - name: 'Check out obscuro-test'
        uses: actions/checkout@v3
        with:
          path: ./obscuro-test

      - name: 'Run funds check'
        run: |
          cd ${{ github.workspace }}/obscuro-test/admin
          /usr/local/bin/pysys.py run -m sepolia check_balances

      - name: 'Discord notification on failure'
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.TESTNET_HEALTH_WEBHOOK }}
          title: "Sepolia funds check failed"
          description: "Sepolia funds check run on schedule"
          content: "Please investigate <@814873419207409685> <@92361563276591104> <@494924753962926120> <@921049923414261821> <@1034771491436363797> <@639076633994592256>"
          avatar_url: ${{ secrets.AVATAR_URL }}