name: Run local tests
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  Run-Tests:
    runs-on: self-hosted
    steps:
      - run: echo "Triggered by ${{ github.event_name }} event running on branch ${{ github.ref }} "

      - name: Check out obscuro-test
        uses: actions/checkout@v3
        with:
          path: ./obscuro-test

      - name: Check out go-obscuro code
        uses: actions/checkout@v3
        with:
          repository: obscuronet/go-obscuro
          path: ./go-obscuro

      - name: Build wallet_extension
        run: |
          cd ${{ github.workspace }}/go-obscuro/tools/walletextension/main
          go build -o ${{ github.workspace }}/obscuro-test/artifacts/wallet_extension
          ls -l ${{ github.workspace }}/obscuro-test/artifacts   

      - name: Docker clean up
        run: |
          for i in `docker ps -a | awk '{ print $1 } ' | grep -v CONTAINER`; do docker stop $i && docker rm $i; done
          docker system prune -a

      - name: Build and run local testnet
        run: |
          cd ${{ github.workspace }}/go-obscuro/testnet
          docker build -t testnetobscuronet.azurecr.io/obscuronet/obscuro_gethnetwork:latest -f gethnetwork.Dockerfile ..
          docker build -t testnetobscuronet.azurecr.io/obscuronet/obscuro_host:latest -f ../dockerfiles/host.Dockerfile ..
          docker build -t testnetobscuronet.azurecr.io/obscuronet/obscuro_contractdeployer:latest -f contractdeployer.Dockerfile ..
          docker build -t testnetobscuronet.azurecr.io/obscuronet/obscuro_enclave:latest -f  ../dockerfiles/enclave.Dockerfile ..
          docker build -t testnetobscuronet.azurecr.io/obscuronet/obscuro_enclave_debug:latest -f ../dockerfiles/enclave.debug.Dockerfile ..
          ./testnet-local-gethnetwork.sh --pkaddresses=0x13E23Ca74DE0206C56ebaE8D51b5622EFF1E9944,0x0654D8B60033144D567f25bF41baC1FB0D60F23B
          sleep 30
          ./testnet-deploy-contracts.sh --l1host=gethnetwork --pkstring=f52e5418e349dccdda29b6ac8b0abe6576bb7713886aa85abea6181ba731f9bb
          sleep 30
          ./start-obscuro-node.sh --sgx_enabled=false --host_id=0x0000000000000000000000000000000000000001 --l1host=gethnetwork --mgmtcontractaddr=0xeDa66Cc53bd2f26896f6Ba6b736B1Ca325DE04eF --hocerc20addr=0xC0370e0b5C1A41D447BDdA655079A1B977C71aA9 --pocerc20addr=0x51D43a3Ca257584E770B6188232b199E76B022A2 --is_genesis=true
          sleep 30
          ./testnet-deploy-l2-contracts.sh --l2host=testnet-host-1

      - name: Run allocations
        run: |
          cd ${{ github.workspace }}/obscuro-test/admin
          /usr/local/bin/pysys.py run -m obscuro.local fund_deploy_native
          /usr/local/bin/pysys.py run -m obscuro.local fund_deploy_tokens
          /usr/local/bin/pysys.py run -m obscuro.local fund_test_users

      - name: Run tests
        run: |
          cd ${{ github.workspace }}/obscuro-test/tests
          /usr/local/bin/pysys.py run -m obscuro.local gen_cor_001: