name: Run Testnet Tests
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        required: true
        default: testnet
        options:
          - testnet
          - dev-testnet

jobs:
  Run-Tests:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Triggered by ${{ github.event_name }}"
      - run: echo "Branch       ${{ github.ref }}"
      - run: echo "Environment  ${{ github.event.inputs.environment }}"

      - name: Check out obscuro-test
        uses: actions/checkout@v3
        with:
          path: ./obscuro-test

      - name: Check out go-obscuro code
        uses: actions/checkout@v3
        with:
          repository: obscuronet/go-obscuro
          path: ./go-obscuro

      - name: Build artifacts
        run: |
          cd ${{ github.workspace }}/go-obscuro/tools/walletextension/main
          go build -o ${{ github.workspace }}/obscuro-test/artifacts/wallet_extension
          ls -l ${{ github.workspace }}/obscuro-test/artifacts

      - name: Install dependencies
        run: |
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:ethereum/ethereum
          sudo apt update
          sudo apt install -y curl
          sudo apt install -y solc
          
          sudo curl -sL https://deb.nodesource.com/setup_18.x | sudo bash -
          sudo apt-get install -y nodejs
          sudo npm install console-stamp --global
          sudo npm install web3 --global 
          sudo npm install commander --global
          sudo npm install ethers --global
          sudo npm list -g

          sudo apt install -y python3-pip
          sudo python3 -m pip install web3
          sudo python3 -m pip install pysys==1.6.1
          sudo python3 -m pip install py-solc-x

      - name: Run tests on testnet on a manual trigger
        if: ${{ github.event.inputs.environment == 'testnet' }}
        run: |
          cd ${{ github.workspace }}/obscuro-test/tests/generic
          /usr/local/bin/pysys.py run -m obscuro.dev -e skip -e events
          cd ${{ github.workspace }}/obscuro-test/tests/obscuro
          /usr/local/bin/pysys.py run -m obscuro.dev -e skip -e events

      - name: Run tests on dev-testnet on a manual trigger
        if: ${{ github.event.inputs.environment == 'dev-testnet' }}
        run: |
          cd ${{ github.workspace }}/obscuro-test/tests/generic
          /usr/local/bin/pysys.py run -m obscuro.dev -e skip -e events
          cd ${{ github.workspace }}/obscuro-test/tests/obscuro
          /usr/local/bin/pysys.py run -m obscuro.dev -e skip -e events

      - name: Upload testcase output
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-artifact
          path: |
            ${{ github.workspace }}/obscuro-test/**/Output
          retention-days: 2
